config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  
  resources :posts do
    resources :comments
  end

  resources :tags

  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :post
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect { |s| s.strip.downcase }.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(posts_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :no_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    def no_authors_or_authenticated 
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	def create
		@comment = Comment.new(comment_params)
		@comment.post_id = params[:post_id]

		@comment.save

		redirect_to post_path(@comment.post)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	def index
		@posts = Post.order("created_at desc").limit(5)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]
	
	include PostsHelper

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		@comment.post_id = @post.id
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.save

		flash.notice = "Post '#{@post.title}' Created!"

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		flash.notice = "Post '#{@post.title}' Deleted!"

		redirect_to posts_path
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)

		flash.notice = "Post '#{@post.title}' Updated!"

		redirect_to post_path(@post)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]
	include TagsHelper
	
	def index
		@tags = Tag.all
	end

	def show
  		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "Tag '#{@tag.name}' Deleted!"

		redirect_to tags_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
	def attachment_params
		params.require(:attachment).permit(:post_id, :image)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_params
		params.require(:post).permit(:title, :body, :tag_list, :attachments)
	end
end

app/helpers/tags_helper.rb
module TagsHelper
	def tag_params
		params.require(:tag).permit(:name)
	end
end

app/views/author_sessions/new.html.erb
<h1>Login</h1>

  <%= form_tag author_sessions_path, method: :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
      <br/>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br/>
    </div>
    <div class="field">
      <%= label_tag :remember %>
      <%= check_box_tag :remember %>
      <br/>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>

<%= link_to 'Back', posts_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<p>

<%= form_for [ @post, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

</p>

app/views/landing/_content.html.erb
<div class="content">
	<div class="content-inner">
	<%= render :partial => 'nav_button' %>
	</div>
</div>

app/views/landing/_header.html.erb
<div class="header">
	<div class="header-inner">
		<div class="logo">
			<h1>RAE FARINE</h1>
		</div>
		<div class="nav">
			<i class="js-menu-trigger sliding-menu-button icon eye-icon"></i>
		</div>
	</div>
</div>

app/views/landing/_intro.html.erb
<section>
	<article>
		<div class="intro">
			<div class="hero-unit">
				<h1>Hello There</h1>
				<p>I am going to be some witty text. I am going to be some witty text. I am going to be some witty text.</p>
			</div>
		</div>
	</article>
</section>

app/views/landing/index.html.erb
<%= render :partial => 'header' %>
<%= render :partial => 'intro' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/components/navigation' %>
<div class="container">
	<p class="flash"><%= flash.notice %></p>
	<%= yield %>
</div>
<%= render :partial => 'layouts/components/footer' %>
</body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="footer-2">

	<div class="bullets">
	  <div class="bullet three-col-bullet">
	    <div class="bullet-icon bullet-icon-1"><i class="icon rss-icon"></i></div>
	    <div class="bullet-content">
	      <h2>Recent Blog Posts</h2>
	      <p><%= render :partial => 'posts/recent' %></p>
	      </div>
	  </div>  
	  <div class="bullet three-col-bullet">
	    <div class="bullet-icon bullet-icon-2"><i class="icon-social git-icon"></i></div>
	    <div class="bullet-content">
	      <h2>Git Commits</h2>
	      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum.</p>
	    </div>
	  </div>
	  <div class="bullet three-col-bullet">
	    <div class="bullet-icon bullet-icon-3"><i class="icon info-icon"></i></div>
	    <div class="bullet-content">
	      <h2>Copyright & Credits</h2>
	      <p>
	        &copy; Copyright 2014 Rae Farine.<br>
	        Entypo pictograms by <%= link_to "Daniel Bruce", "http://www.entypo.com/" %>.
	        <% if logged_in? %>
	        <li class= "login-name"><%= "Logged in as #{current_user.email}" %></li>
	        <li><%= link_to "New Post", new_post_path, class: "new_post" %></li>
	        <li><%= link_to "Logout", logout_path %></li>
	        <% else %>
	          <li><%= link_to "Login", login_path %></li>
	        <% end %>
	      </p>
	    </div>
	  </div> 
	</div>
  
</footer>

app/views/layouts/components/_navigation.html.erb
<nav class="js-menu sliding-menu-content">
  <ul>
    <li class="home"><a href="javascript:void(0)"><i class="home-icon icon"></i></a></li>
    <li><a href="javascript:void(0)">About</a></li>
    <li><a href="javascript:void(0)">Blog</a></li>
    <li><a href="javascript:void(0)">Resume</a></li>
    <li><a href="javascript:void(0)">Contact</a></li>
  </ul>
</nav>

<div class="js-menu-screen menu-screen"></div>

<script>
  $(document).ready(function(){

    $('.js-menu-trigger').on('click touchstart', function(e){
      $('.js-menu').toggleClass('is-visible');
      $('.js-menu-screen').toggleClass('is-visible');
      e.preventDefault();
    });

    $('.js-menu-screen').on('click touchstart', function(e){
      $('.js-menu').toggleClass('is-visible');
      $('.js-menu-screen').toggleClass('is-visible');
      e.preventDefault();
    });
  });
</script>

app/views/posts/_comment.html.erb
<div class="comment">
  <div class="comment-image">
    <img src="http://placehold.it/85x85">
  </div>
  <div class="comment-content">
    <h1><%= comment.author_name %></h1>
    <p><%= comment.body %></p>
    <p class="comment-detail">Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> later</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <ul>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <% if @post.attachments %>
      <% @post.attachments.each do |a| %>
        <%= image_tag a.image.url %><br/>
      <% end %>
    <% end %>
    <%= f.label :attachment, "Attach a New Image" %><br />
    <%= f.file_field "images[]", type: :file, multiple: true %>
  </p>
  <p>
    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, "Post Text" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_landing.html.erb
<h1>All Posts</h1>

<% if logged_in? %>
  <%= link_to "Create a New Post", new_post_path, class: "new_post" %>
<% end %>

<ul id="posts">
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

app/views/posts/_recent.html.erb
<ul id="posts">
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %></h1>

<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% if logged_in? %>
  <%= link_to "Create a New Post", new_post_path, class: "new_post" %>
<% end %>

<ul id="posts">
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<p>
  Tags:
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<% if logged_in? %>
  <%= link_to "Edit", edit_post_path(@post) %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Really delete the article?"} %>
<% end %>

<br><br>

<h3>Comments (<%= @post.comments.size %>)</h3>
<%= render partial: 'posts/comment', collection: @post.comments %>
<%= render partial: 'comments/form' %>

<br><br>

<%= link_to "<< Back to Posts List", posts_path %>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
	  [<%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"} %>]
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Posts Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>